### ISSUE TITLE
Mutation Component - Property 'x' does not exist on type 'void | FetchResult<MutationResponse, Record<string, any>, Record<string, any>>'.   Property 'x' does not exist on type 'void'.

### ISSUE THREAD

**Issue by BrunoQuaresma** [apollographql/react-apollo#3032]
I have the following component:
```javascript
import React, { useState } from 'react';
import { RouteComponentProps } from '@reach/router';
import { Mutation, MutationFn } from 'react-apollo';
import gql from 'graphql-tag';
import useForm from './utils/form';
import { saveToken } from './modules/security';

type LoginResponse = {
  login: {
    token: string;
  };
};

type LoginInput = {
  email: string;
  password: string;
};

const LOGIN = gql`
  mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      token
    }
  }
`;

const initialFormValues = {
  email: '',
  password: ''
};

const LoginScreen = (props: RouteComponentProps) => {
  const [formError, setFormError] = useState<boolean>(false);
  const { formValues, handleFieldChange } = useForm<LoginInput>(
    initialFormValues
  );

  async function handleSubmit(
    event: React.FormEvent<HTMLFormElement>,
    login: MutationFn<LoginResponse, LoginInput>
  ) {
    event.preventDefault();

    const data = await login({ variables: formValues })
    
    saveToken(data.login.token);
  }

  return (
    <>
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-md-4">
            <div className="card mt-5">
              <div className="card-body">
                <Mutation<LoginResponse, LoginInput> mutation={LOGIN}>
                  {login => {
                    return (
                      <form onSubmit={event => handleSubmit(event, login)}>
                        <h3 className="mb-4">Entrar</h3>
                        <div className="form-group">
                          <label htmlFor="">E-mail</label>
                          <input
                            type="email"
                            name="email"
                            required
                            className="form-control"
                            onChange={handleFieldChange}
                          />
                        </div>

                        <div className="form-group">
                          <label htmlFor="">Senha</label>
                          <input
                            type="password"
                            name="password"
                            required
                            className="form-control"
                            onChange={handleFieldChange}
                          />
                        </div>

                        <div className="form-group">
                          <button className="btn btn-primary btn-block">
                            Entrar
                          </button>
                        </div>
                      </form>
                    );
                  }}
                </Mutation>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default LoginScreen;
```
But when I try to access the `data.login.token` I'm getting this type error:
```
Property 'login' does not exist on type 'void | FetchResult<LoginResponse, Record<string, any>, Record<string, any>>'.
  Property 'login' does not exist on type 'void'.ts(2339)
```
I tried to found a solution without success.

**Comment by Marcelo-Figueiredo** [comment]
I'm having the same problem. I've got it to work on react-apollo version 2.1.11, but the newer ones don't.

Have you found any way to solve it?

**Comment by jasonpaulos** [comment]
Hi @BrunoQuaresma, notice that the return type of `MutationFn<TData, TVariables>` is `Promise<void | FetchResult<TData>>` according to its definition [here](https://github.com/apollographql/react-apollo/blob/98ef97a57689fe581dc45af4327470b68518fb8a/src/Mutation.tsx#L60). Specifically, the function will resolve to void if `ignoreResults` is true for the mutation, as stated in the documentation: https://www.apollographql.com/docs/react/essentials/mutations/#render-prop-function

In your case, you should be able to check if `data` is not void, then save your token. Hope this helps!
