### ISSUE TITLE
v3.0.0-beta.3: Hooks error when running test

### ISSUE THREAD

**Issue by huboo** [apollographql/react-apollo#3169]
**Intended outcome:**

I am using **react-apollo@3.0.0-beta.3** hooks feature and when I run test I want custom hooks with **MockedProvider** can return mock result.

**Actual outcome:**

I got this error with **react-test-renderer** renderer:

_Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an &lt;ApolloProvider&gt;, or pass an ApolloClient instance in via options._

I also tried **@testing-library/react-hooks** renderHook to test only the hook then I got error:

_TypeError: Cannot read property 'getCurrentResult' of undefined_

**How to reproduce the issue:**

You can find code here (not runnable in sandbox)
https://codesandbox.io/s/apollo-client-error-template-qh1hk

**Version**

  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 8.15.1 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0
    Safari: 12.1.1
  npmPackages:
    apollo-boost: ^0.3.1 =&gt; 0.3.1
    apollo-cache-inmemory: ^1.5.1 =&gt; 1.5.1
    react-apollo: ^3.0.0-beta.3 =&gt; 3.0.0-beta.3
    react: ^16.8.5 =&gt; 16.8.5
    react-dom: ^16.8.5 =&gt; 16.8.5
    @apollo/react-testing: 0.1.0-beta.5 =&gt; 0.1.0-beta.5
    @testing-library/react-hooks: ^1.0.4 =&gt; 1.0.4
    react-test-renderer: ^16.8.6 =&gt; 16.8.6

In the previous version of react-apollo@3.0.0.beta.2 and @apollo/react-testing@0.1.0-beta.4 the MockedProvider works fine.

Could you please take a look at thank you in advance very much.

**Comment by hwillson** [comment]
Thanks for reporting this @huboo. Can you try bumping your `apollo-boost` version to 0.4.3, to see if that helps?

**Comment by huboo** [comment]
> Thanks for reporting this @huboo. Can you try bumping your `apollo-boost` version to 0.4.3, to see if that helps?

After update apollo-boost to 0.4.3 the error "resetQueryStoreErrors is not a function" in browser console is gone but running test still report error.

Thank you for your time.
