### ISSUE TITLE
Typescript throw a bunch of errors

### ISSUE THREAD

**Issue by sammkj** [apollographql/react-apollo#765]
## Steps to Reproduce

Describe how to reproduce this issue.

```
git clone https://github.com/sammkj/react-apollo-typescript-error
cd react-apollo-typescript-error
yarn install
yarn run build

# check terminal to see errors
```

Repo: https://github.com/sammkj/react-apollo-typescript-error

### Buggy Behavior

Typescript throws the following errors when building the app:

```
ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:41 
    TS1005: ',' expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:43 
    TS1005: '>' expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:45 
    TS1128: Declaration or statement expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:118 
    TS1005: ')' expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:151 
    TS1109: Expression expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:185 
    TS1005: '(' expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:186 
    TS1005: ';' expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:227 
    TS1005: '(' expected.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:47 
    TS2304: Cannot find name 'TProps'.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:60 
    TS2304: Cannot find name 'TChildProps'.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:74 
    TS2693: 'DefaultChildProps' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:92 
    TS2304: Cannot find name 'TProps'.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:100 
    TS2304: Cannot find name 'TResult'.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:109 
    TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:120 
    TS2693: 'DocumentNode' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:120 
    TS2695: Left side of comma operator is unused and has no side effects.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:134 
    TS2304: Cannot find name 'operationOptions'.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:153 
    TS2693: 'OperationOption' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/react-apollo/lib/graphql.d.ts:59:188 
    TS2693: 'ComponentDecorator' only refers to a type, but is being used as a value here.
```

### Expected Behavior

It shouldn't have thrown any errors.

### Version
- apollo-client@^1.4.1
- react-apollo@^1.4.2

**Comment by sammkj** [comment]
It seems this issue is happening is because I'm using v2.2.2 Typescript which doesn't support generic parameter defaults. My company still hasn't migrated over to v2.3 and above. Would it be possible to have `react-apollo` support v2.2.2?

**Comment by helfer** [comment]
Hm, I see. What's the latest version of react-apollo that works with 2.2? I don't think we can maintain compatibility with 2.2 on the master branch, but if it's not too much work, you could maintain it on a separate branch that we release under a different tag. What do you think?

**Comment by sammkj** [comment]
I brought up this issue in our briefing and decided that we're gonna migrate to v2.3 TS this week. :smile:

**Comment by helfer** [comment]
Haha, that's one way to solve the problem 😁
